src/dpc.Web/Controllers/ProgramController.cs
using AutoMapper;
using dpc.Business.Interfaces;
using dpc.Data;
using dpc.Data.CustomModels;
using dpc.Web.Extensions;
using dpc.Web.ViewModel;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using dpc.Common;

namespace dpc.Web.Controllers
{
	[Authorize]
	[ClaimsAccess(ClaimType = ClaimType.Role, Value = ClaimValue.Sales)]
	public class ProgramController : BaseController
	{
		#region constructors 

		private readonly IProgramManager _programManager;

		public ProgramController(IProgramManager programManager)
		{
			_programManager = programManager;
		}

		#endregion constructors

		// GET: Program
		public ActionResult Index()
		{
			return View();
		}

		// GET: Program/CreateHeader
		public ActionResult CreateHeader()
		{
			var vm = new ProgramHeaderViewModel();

			vm.BrandOwnerList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetBrandOwnerList());
			vm.TransitionTypeList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetTransitionTypeList());
			vm.PalletsList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetYesNoList());
			vm.NewProgramList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetYesNoList());
			vm.FreightTermsList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetFreightTermsList());

			return View(vm);
		}

		// POST: Program/CreateHeader
		[HttpPost]
		public ActionResult CreateHeader(ProgramHeaderViewModel vm, FormCollection collection)
		{
			vm.BrandOwnerList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetBrandOwnerList());
			vm.TransitionTypeList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetTransitionTypeList());
			vm.PalletsList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetYesNoList());
			vm.NewProgramList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetYesNoList());
			vm.FreightTermsList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetFreightTermsList());

			if (collection["Create"] != null)
			{
				if (!ModelState.IsValid)
				{
					return View(vm);
				}

				vm.Status = _programManager.GetProgramStatus(vm.ProgramHeaderId);
				vm.ProductCategoryId = 1;  //TODO: Get ProductCategoryId from Main menu selection (i.e. Baby or Adult)
				var model = Mapper.Map<ProgramHeaderViewModel, ProgramHeader>(vm);
				_programManager.InsertProgramHeader(model);

				//Update ProgramHeader Status
				_programManager.UpdateProgramHeaderStatus(model.ProgramHeaderId);

				return RedirectToAction("Index");
			}

			return View(vm);
		}

		// GET: Program/EditHeader/5
		public ActionResult EditHeader(int id)
		{
			if (!(id > 0))
			{
				throw new ArgumentException(String.Format("{0} is an invalid parameter", id), "id");
			}

			var model = _programManager.GetProgramHeaderById(id);
			var vm = Mapper.Map<ProgramHeader, ProgramHeaderViewModel>(model);

			vm.BrandOwnerList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetBrandOwnerList());
			vm.TransitionTypeList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetTransitionTypeList());
			vm.PalletsList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetYesNoList());
			vm.NewProgramList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetYesNoList());
			vm.FreightTermsList = Mapper.Map<IEnumerable<SelectModel>, IEnumerable<SelectViewModel>>(_programManager.GetFreightTermsList());
			vm.ProgramLineCount = _programManager.GetProgramLinesByProgramHeaderId(id).Count();

			vm.isProgramLinesExist = false;
			if (vm.ProgramLineCount > 0)
			{
				vm.isProgramLinesExist = true;
			}

			//Define button status
			vm.isProgramSubmitted = _programManager.isProgramSubmitted(id);
			vm.isProgramRejected = _programManager.isProgramRejected(id);
			vm.isProgramApproved = _programManager.isProgramApproved(id);

			return View(vm);
		}

		// POST: Program/EditHeader
		[HttpPost]
		[AllowAnonymous]
		public async Task<ActionResult> EditHeader(ProgramHeaderViewModel vm)
		{
			var programStatus = _programManager.GetProgramStatus(vm.ProgramHeaderId);

			//Submit for Approval...
			var programHeader = _programManager.GetProgramHeaderById(vm.ProgramHeaderId);
			_programManager.UpdateSubmitForApproval(programHeader);

			//TODO: change "Approver-Retail" to use RoleId... also fix claims to use RoleId rather than string
			var programApproverList = Mapper.Map<IEnumerable<ProgramApproverModel>, IEnumerable<ProgramApproverViewModel>>(_programManager.GetProgramApproverList("Approver-" + vm.BusinessUnit));

			//Send email to Approvers
			var programHeaderInfo = _programManager.GetProgramHeaderInfoById(vm.ProgramHeaderId);
			var programApprovalPath = Convert.ToString(ConfigurationManager.AppSettings["ProgramApprovalPath"]);
			var callbackUrl = programApprovalPath + vm.ProgramHeaderId;
			foreach (var approver in programApproverList)
			{
				if (programStatus == EnumProgramStatus.Rejected || programStatus == EnumProgramStatus.Evaluating || programStatus == EnumProgramStatus.ReEvaluating)
				{
					//Send re-approve email if Program was rejected
					await UserManager.SendEmailAsync(approver.UserId, 
						"** TESTING ** - LAR Re-Approve Program Request: " + vm.ProgramHeaderId,
						"Program re-approval requested... " +
						"<br/>Title:       <b>" + programHeaderInfo.Title + "</b>" +
						"<br/>Brand Owner: <b>" + programHeaderInfo.BrandOwnerDescription + "</b>" +
						"<br/>Created on:  <b>" + programHeaderInfo.CreatedOn.ToShortDateString() + "</b> by: <b>" + programHeaderInfo.CreatedBy + "</b>" +
						"<br/>Comments:    <b>" + programHeaderInfo.Comments + "</b>" +
						"<br/><br/>Program was previously rejected and now needs to be re-viewed by clicking <a href=\"" + callbackUrl + "\">here</a>");
				}
				else
				{
					//Send approve email if Program was rejected
					await UserManager.SendEmailAsync(approver.UserId, 
						"** TESTING ** - LAR Approve Program Request: " + vm.ProgramHeaderId,
						"Program approval requested... " +
						"<br/>Title:       <b>" + programHeaderInfo.Title + "</b>" +
						"<br/>Brand Owner: <b>" + programHeaderInfo.BrandOwnerDescription + "</b>" +
						"<br/>Created on:  <b>" + programHeaderInfo.CreatedOn.ToShortDateString() + "</b> by: <b>" + programHeaderInfo.CreatedBy + "</b>" +
						"<br/>Comments:    <b>" + programHeaderInfo.Comments + "</b>" +
						"<br/><br/>Please review Program by clicking <a href=\"" + callbackUrl + "\">here</a>");

					//Insert Approvers into ProgramApproval table (user will update when approving Program)
					var programApproval = new ProgramApproval();
					programApproval.ProgramHeaderId = vm.ProgramHeaderId;
					programApproval.ApproverUserId = approver.UserId;
					_programManager.InsertProgramApproval(programApproval);
				}
			}

			//Update ProgramHeader Status
			_programManager.UpdateProgramHeaderStatus(vm.ProgramHeaderId);

			return RedirectToAction("Index");
		}

		[HttpGet]
		public async Task<ActionResult> GetProgramHeaderByIdAsync(string id)
		{
			var model = await _programManager.GetProgramHeaderByIdAsync(int.Parse(id));
			var vm = model.ToViewModel();

			return PartialView("_ProgramHeaderFinancials", vm);
		}

		// GET: Program/CreateLine
		public ActionResult CreateLine(int id)
		{
			var vm = new ProgramLineExtViewModel();
			vm.ProgramHeader = new ProgramHeaderViewModel();
			vm.ProgramHeader = Mapper.Map<ProgramHeaderViewModel>(_programManager.GetProgramHeaderById(id));

			IEnumerable<Feature> features = _programManager.GetFeaturesByProductCategory(vm.ProgramHeader.ProductCategoryId);

			vm.FeatureList = Mapper.Map<IEnumerable<Feature>, IEnumerable<FeatureViewModel>>(features);

			vm.FeatureOptions = _programManager.GetProgramLinesDataByProgramHeaderId(id);

			//Disable buttons (Create) if Submitted for Approval
			vm.isApprovalSubmitted = _programManager.isProgramSubmitted(id);

			return View(vm);
		}

		// POST: Program/CreateLine
		[HttpPost]
		public ActionResult CreateLine(ProgramLineExtViewModel vm)
		{
			return View(vm);
		}

		// GET: Program/Reports/1
		public void ReportXlsx(int id)
		{
			Telerik.Reporting.Report report = new Report.CostModel(id);

			ExportReportXlsx(report);
		}

		// GET: Program/Approval/1
		public ActionResult Approval(int id)
		{
			var vm = new ProgramApprovalViewModel();
			vm.ProgramHeader = Mapper.Map<ProgramHeaderViewModel>(_programManager.GetProgramHeaderById(id));

			//Get Approvers from Identity
			vm.ApproverList = Mapper.Map<IEnumerable<ProgramApproverModel>, IEnumerable<ProgramApproverViewModel>>(_programManager.GetProgramApproverListByProgramHeaderId("Approver-" + vm.ProgramHeader.BusinessUnit, id));

			//Check if logged in user is an Approver
			foreach (var approver in vm.ApproverList)
			{
				if (User.Identity.GetUserId() == approver.UserId)
				{
					approver.isReadOnly = false;
				}
				else
				{
					approver.isReadOnly = true;
				}
			}

			//Define button status
			vm.ProgramHeader.isProgramSubmitted = _programManager.isProgramSubmitted(id);
			vm.ProgramHeader.isProgramRejected = _programManager.isProgramRejected(id);
			vm.ProgramHeader.isProgramApproved = _programManager.isProgramApproved(id);

			return View(vm);
		}

		// POST: Program/Approval
		[HttpPost]
		public ActionResult Approval(ProgramApprovalViewModel vm)
		{
			//Save approved info
			var programApproval = _programManager.GetProgramApprovalById(vm.ProgramApprovalId);
			programApproval.Comment = vm.Comment;

src/dpc.Web/Controllers/ReportsController.cs
using System;
using Telerik.Reporting.Services.WebApi;

namespace dpc.Web.Controllers
{
	//NOTE: NOT CURRENTLY BEING USED - USED ONLY WITH REPORTVIEWER
	public class ReportsController : ReportsControllerBase
	{
#pragma warning disable CS0672 // Member overrides obsolete member
		protected override Telerik.Reporting.Cache.Interfaces.ICache CreateCache()
#pragma warning restore CS0672 // Member overrides obsolete member
		{
			return Telerik.Reporting.Services.Engine.CacheFactory.CreateFileCache();
		}

#pragma warning disable CS0672 // Member overrides obsolete member
		protected override Telerik.Reporting.Services.Engine.IReportResolver CreateReportResolver()
#pragma warning restore CS0672 // Member overrides obsolete member
		{
			return new CustomReportResolver();
		}
	}

	class CustomReportResolver : Telerik.Reporting.Services.Engine.IReportResolver
	{
		public Telerik.Reporting.ReportSource Resolve(string reportId)
		{
			Telerik.Reporting.Report report = new Report.CostModel(Int32.Parse(reportId));

			var irs = new Telerik.Reporting.InstanceReportSource();
			irs.ReportDocument = report;

			return irs;
		}
	}
}

src/dpc.Web/Views/Program/Approval.cshtml
@model dpc.Web.ViewModel.ProgramApprovalViewModel

@{
	ViewBag.Title = "Approvals";
}

<h3>@ViewBag.Title for Program: @Html.DisplayFor(model => model.ProgramHeader.ProgramHeaderId) (@Html.DisplayFor(model => model.ProgramHeader.Status))</h3>
<hr />

@Html.AntiForgeryToken()

<style>
	fieldset.approver-border {
		border: 1px groove #ddd !important;
		padding: 0 1.4em 1.4em 1.4em !important;
		margin: 0 0 1.5em 0 !important;
		-webkit-box-shadow: 0px 0px 0px 0px #000;
		box-shadow: 0px 0px 0px 0px #000;
	}

	legend.approver-border {
		width: inherit; /* Or auto */
		padding: 0 10px; /* To give a bit of padding on the left and right */
		border-bottom: none;
		font-size: 1em;
	}
</style>

<div>
	@if (Model != null)
	{

		foreach (var approver in Model.ApproverList)
		{
			var approvedFlag = "";
			var commentOn = String.Empty;

			{ Model.ProgramApprovalId = @approver.ProgramApprovalId; }

			if (@approver.Approved == true)
			{
				approvedFlag = "true";
			}
			else if (@approver.Approved == false)
			{
				approvedFlag = "false";
			}

			if (@approver.CommentOn != null)
			{
				commentOn = @approver.CommentOn.ToString();
			}

			if (@approver.Comment != null)
			{
				Model.Comment = @approver.Comment;
			}
			else
			{
				Model.Comment = String.Empty;
			}


			if ((approver.isReadOnly && commentOn != String.Empty) || Model.ProgramHeader.isProgramApproved)
			{
				<div class="form-group">
					<fieldset disabled class="approver-border">
						<legend class="approver-border"><b>Approver:</b> @approver.FirstName @approver.LastName</legend>
						<div class="col-md-4">
							@if (approvedFlag == "true")
							{
								<input type="radio" checked="checked"><span>&nbsp;&nbsp;Approved&nbsp;&nbsp;&nbsp;&nbsp;</span>
								<input type="radio"><span>&nbsp;Rejected</span>
							}
							else
							{
								<input type="radio"><span>&nbsp;&nbsp;Approved&nbsp;&nbsp;&nbsp;&nbsp;</span>
								<input type="radio" checked="checked"><span>&nbsp;Rejected</span>
							}
							<br /><br />
							@Html.Label(commentOn, new { style = "font-weight: lighter;" })
						</div>
						<div class="col-md-5">
							@Html.Label("Comment", htmlAttributes: new { style = "font-weight: lighter;" })
							@Html.TextAreaFor(model => model.Comment, new { @class = "form-control", @rows = 3 })
						</div>
					</fieldset>
				</div>
			}
			else if (!approver.isReadOnly)
			{
				using (Html.BeginForm(null, null, FormMethod.Post, new { name = "formApproval", id = "formApproval" }))
				{
					<div class="form-group">
						<fieldset class="approver-border">
							@Html.HiddenFor(model => model.ProgramHeader.ProgramHeaderId)
							@Html.HiddenFor(model => model.ProgramApprovalId)

							<legend class="approver-border"><b>Approver:</b> @approver.FirstName @approver.LastName</legend>
							<div class="col-md-4">
								@if (approvedFlag == "true")
								{
									@Html.Kendo().RadioButtonFor(model => model.Approved).Checked(true).Label("Approved").Value(true)
									@Html.Kendo().RadioButtonFor(model => model.Approved).Checked(false).Label("Rejected").Value(false).HtmlAttributes(new { @style = "margin-left: 20px;" })}
								else
								{
									@Html.Kendo().RadioButtonFor(model => model.Approved).Checked(false).Label("Approved").Value(true)
									@Html.Kendo().RadioButtonFor(model => model.Approved).Checked(true).Label("Rejected").Value(false).HtmlAttributes(new { @style = "margin-left: 20px;" })
								}
								<br /><br />
								@if (commentOn != String.Empty)
								{
									@Html.Label(commentOn, new { htmlAttributes = new { @class = "control-label" } })
								}
							</div>
							<div class="col-md-5">
								@Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label" })
								@Html.TextAreaFor(model => model.Comment, new { @class = "form-control", @rows = 3, autofocus = "autofocus" })
							</div>
							<br />
							<div class="form-group">
								@if (Model.ProgramHeader.isProgramSubmitted && Model.ProgramHeader.isProgramApproved)
								{
									<span class="tool-tip" data-toggle="tooltip" data-placement="bottom" title="Program Approved">
										<input id="Save" name="Save" type="submit" value="Save" class="btn btn-primary" disabled="disabled" />
									</span>
									@Html.ActionLink("Cancel", "Index", "Program", null, new { @class = "btn btn-danger" })
								}
								else if (Model.ProgramHeader.isProgramSubmitted && !Model.ProgramHeader.isProgramRejected && !Model.ProgramHeader.isProgramApproved)
								{
									<input id="Save" name="Save" type="submit" value="Save" class="btn btn-primary" title="Save or Update Approval" data-toggle='tooltip' data-placement="bottom" />
									@Html.ActionLink("Cancel", "Index", "Program", null, new { @class = "btn btn-danger" })
								}
								else if (Model.ProgramHeader.isProgramSubmitted && Model.ProgramHeader.isProgramRejected)
								{
									<span class="tool-tip" data-toggle="tooltip" data-placement="bottom" title="Program Rejected pending updates and re-submit">
										<input id="Save" name="Save" type="submit" value="Save" class="btn btn-primary" disabled="disabled" />
									</span>
									@Html.ActionLink("Cancel", "Index", "Program", null, new { @class = "btn btn-danger" })
								}
								else
								{
									<span class="tool-tip" data-toggle="tooltip" data-placement="bottom" title="Program Locked">
										<input id="Save" name="Save" type="submit" value="Save" class="btn btn-primary disabled" disabled="disabled" />
									</span>
									@Html.ActionLink("Cancel", "Index", "Program", null, new { @class = "btn btn-danger" })
								}

							</div>
						</fieldset>
					</div>
				}
			}
			else
			{
				<div class="form-group">
					<fieldset class="approver-border">
						<legend class="approver-border"><b>Approver:</b> @approver.FirstName @approver.LastName</legend>
						<div>Pending Approval</div>
					</fieldset>
				</div>
			}
		}
	}
	<br />
	<div>
		@Html.ActionLink("Back to Manage Programs", "Index")
	</div>
</div>
<style>
	.x-text-readonly {
		font-weight: lighter;
	}
</style>


@section Scripts {
	@Scripts.Render("~/Scripts/custom/Program.Approval.js")
}

src/dpc.Web/Views/Program/Index.cshtml
@model IEnumerable<dpc.Web.ViewModel.ProgramHeaderViewModel>

@{
    ViewBag.Title = "Manage Programs";
}

<h3>@ViewBag.Title</h3>

<div>
    <div class="pull-left">
        <p>@Html.ActionLink("Create New", "CreateHeader", null, new { @class = "btn btn-primary" })</p>
    </div>
    <div class="pull-right">
        @*<p class="text-right"><a href="~/Content/images/LAR Program 20160926.png" target="_blank" title="Opens ERD (Entity Relationship Diagram) image in a new window">Temp link... Data Relationship</a></p>*@
    </div>
    <div class="clearfix"></div>
</div>

@(Html.Kendo().Grid<dpc.Web.ViewModel.ProgramHeaderViewModel>()
		.Name("grid")
		.HtmlAttributes(new { style = "height:600px; width:100%;" })
		.Columns(columns =>
		{
			columns.Template(x => { }).Width(26).ClientTemplate(
				"<a title='Program Details' data-toggle='tooltip' data-placement='right' href='" + Url.Action("EditHeader", "Program") + "/#=ProgramHeaderId#'><i class='fa fa-pencil fa-lg'></i></a>&nbsp;&nbsp;&nbsp;" +
				"# if (Status == 1) { #" +
					"<a title='Approval not Submitted' data-toggle='tooltip' data-placement='right'><i class='fa fa-hand-o-right fa-lg x-icon-inactive'></i></a>&nbsp;&nbsp;&nbsp;" +
				"# } else { #" +
					"<a title='View Approvals' data-toggle='tooltip' data-placement='right' href='" + Url.Action("Approval", "Program") + "/#=ProgramHeaderId#'><i class='fa fa-hand-o-right fa-lg'></i></a>&nbsp;&nbsp;&nbsp;" +
				"# } #" +
				"<a title='View Report' data-toggle='tooltip' data-placement='right' href='" + Url.Action("ReportXlsx", "Program", new { id = "#=ProgramHeaderId#" }) + "'><i class='fa fa-file-excel-o fa-lg'></i></a>&nbsp;&nbsp;&nbsp;"
					);
			columns.Bound(x => x.ProgramHeaderId).Width(30).HtmlAttributes(new { style = "text-align:right" });
			columns.Bound(x => x.Status).Width(28).HtmlAttributes(new { style = "text-align:center" });
			columns.Bound(x => x.BusinessUnit).Width(35);
			columns.Bound(x => x.Title).Width(50);
			columns.Bound(x => x.BrandOwnerDescription).Width(40);
			columns.Bound(x => x.RequestedShipDate).Width(35).HtmlAttributes(new { style = "text-align:right" });
			columns.Bound(x => x.ContractEndDate).Width(35).HtmlAttributes(new { style = "text-align:right" });
		})
		.Events(e =>
		{
			e.DataBound("OnGridItemsDataBound");
		})
		.Pageable()
		.Resizable(resize => resize.Columns(true))
		.Sortable()
		.Scrollable()
		.Filterable()
		.ToolBar(tools => tools.Excel())
		.Excel(excel => excel
			.AllPages(true)
			.FileName("ProgramsExport.xlsx")
		)
		.DataSource(dataSource => dataSource
			.Ajax()
			.Read(read => read.Action("ProgramHeader_Read", "Program"))
			.PageSize(15)
			.Sort(sort => sort.Add("ProgramHeaderId").Descending())
		)
)

<br />
<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

@section Scripts {
	@Scripts.Render("~/Scripts/custom/Program.Index.js")
}

src/dpc.Web/Views/Program/Reports.cshtml
@using Telerik.ReportViewer.Mvc
@{
    ViewBag.Title = "Reporting";
}

<div style="margin-bottom: -20px">
    <div class="pull-left">
        <h3>@ViewBag.Title</h3>
    </div>
    <div class="pull-right" style="margin-top: 25px">
        <p>@Html.ActionLink("Back to Manage Programs", "Index")</p>
    </div>
    <div class="clearfix"></div>
</div>

<style>
    #reportViewerCostModel {
        position: absolute;
        left: 40px;
        right: 50px;
        top: 165px;
        bottom: 75px;
        overflow: hidden;
        font-family: Verdana, Arial;
    }
</style>

@{
    var uriRS = new UriReportSource() { Uri = ViewBag.ProgramHeaderId.ToString() };
}

@(Html.TelerikReporting().ReportViewer()
        .Id("reportViewerCostModel")
        .ServiceUrl(Url.Content("~/api/reports/"))
        .TemplateUrl(Url.Content("~/ReportViewer/templates/telerikReportViewerTemplate-FA.html"))
        .ReportSource(uriRS)
        .ViewMode(ViewMode.PrintPreview)
        .ScaleMode(ScaleMode.Specific)
        .Scale(1.0)
        .PersistSession(false)
        .PrintMode(PrintMode.AutoSelect)
        .Deferred()
)

@section scripts
{
    @(Html.TelerikReporting().DeferredScripts())
}