src/dpc.Web/Models/ApplicationRole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNet.Identity.EntityFramework;

namespace dpc.Web.Models
{
    public class ApplicationRole : IdentityRole
    {
        public ApplicationRole()
        {
            
        }

        public ApplicationRole(string name) : base(name)
        {
            
        }
    }
}

src/dpc.Web/ViewModels/ApplicationRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace dpc.Web.ViewModels
{
    public class ApplicationRoleViewModel
    {
        public string Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "You must enter a name for the Role.")]
        [StringLength(256, ErrorMessage = "The role name must be 256 characters or shorter.")]
        [Display(Name = "Role Name")]
        public string Name { get; set; }
    }
}

src/dpc.Web/Controllers/ApplicationRolesController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using dpc.Business;
using dpc.Web.Models;
using dpc.Web.ViewModels;

namespace dpc.Web.Controllers
{
	[ClaimsAccess(ClaimType = "Role", Value = "Admin")]
	public class ApplicationRolesController : BaseController
	{
		private DataManager _dataManager;

		public ApplicationRolesController()
		{
		}
		
		public ApplicationRolesController(DataManager dataManager)
		{
			_dataManager = dataManager;
		}

		// GET: ApplicationRoles
		public async Task<ActionResult> Index()
		{
			return View(await RoleManager.Roles.OrderBy(x => x.Name).ToListAsync());
		}

		// GET: ApplicationRoles/Details/5
		public async Task<ActionResult> Details(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ApplicationRole applicationRole = await RoleManager.FindByIdAsync(id);
			if (applicationRole == null)
			{
				return HttpNotFound();
			}
			return View(applicationRole);
		}

		// GET: ApplicationRoles/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: ApplicationRoles/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create([Bind(Include = "Name")] ApplicationRoleViewModel applicationRoleViewModel)
		{
			if (ModelState.IsValid)
			{
				ApplicationRole applicationRole = new ApplicationRole { Name = applicationRoleViewModel.Name };

				var roleResult = await RoleManager.CreateAsync(applicationRole);
				if (!roleResult.Succeeded)
				{
					ModelState.AddModelError("", roleResult.Errors.First());
					return View();
				}

				return RedirectToAction("Index");
			}

			return View();
		}

		// GET: ApplicationRoles/Edit/5
		public async Task<ActionResult> Edit(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ApplicationRole applicationRole = await RoleManager.FindByIdAsync(id);
			if (applicationRole == null)
			{
				return HttpNotFound();
			}

			ApplicationRoleViewModel applicationRoleViewModel = new ApplicationRoleViewModel
			{
				Id = applicationRole.Id,
				Name = applicationRole.Name
			};

			return View(applicationRoleViewModel);
		}

		// POST: ApplicationRoles/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] ApplicationRoleViewModel applicationRoleViewModel)
		{
			if (ModelState.IsValid)
			{
				ApplicationRole applicationRole = await RoleManager.FindByIdAsync(applicationRoleViewModel.Id);
				string originalName = applicationRole.Name;

				if (originalName == "Admin" && applicationRoleViewModel.Name != "Admin")
				{
					ModelState.AddModelError("", "You cannot change the name of the Admin role.");
					return View(applicationRoleViewModel);
				}

				if (originalName != "Admin" && applicationRoleViewModel.Name == "Admin")
				{
					ModelState.AddModelError("", "You cannot change the name of a role to Admin.");
					return View(applicationRoleViewModel);
				}

				applicationRole.Name = applicationRoleViewModel.Name;
				await RoleManager.UpdateAsync(applicationRole);

				return RedirectToAction("Index");
			}
			return View(applicationRoleViewModel);
		}

		// GET: ApplicationRoles/Delete/5
		public async Task<ActionResult> Delete(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ApplicationRole applicationRole = await RoleManager.FindByIdAsync(id);
			if (applicationRole == null)
			{
				return HttpNotFound();
			}
			return View(applicationRole);
		}

		// POST: ApplicationRoles/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> DeleteConfirmed(string id)
		{
			ApplicationRole applicationRole = await RoleManager.FindByIdAsync(id);

			if (applicationRole.Name.ToUpper() == "ADMIN")
			{
				ModelState.AddModelError("", "You cannot delete the Admin role.");
				return View(applicationRole);
			}

			//Verify user does not have a Claim before deleting
			bool isThisRoleUsed = _dataManager.isRoleInClaim(applicationRole.Name);

			if (isThisRoleUsed)
			{
				ModelState.AddModelError("", "Error: Cannot delete role - at least one user has this role");
				return View(applicationRole);
			}
			else
			{
				await RoleManager.DeleteAsync(applicationRole);
				return RedirectToAction("Index");
			}
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				RoleManager.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

src/dpc.Web/Views/ApplicationRoles/Create.cshtml
@model dpc.Web.ViewModels.ApplicationRoleViewModel

@{
    ViewBag.Title = "Create Role";
}

<h3>@ViewBag.Title</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />&nbsp;&nbsp;
                @Html.ActionLink("Cancel", "Index", "ApplicationRoles", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/dpc.Web/Views/ApplicationRoles/Delete.cshtml
@model dpc.Web.Models.ApplicationRole

@{
    ViewBag.Title = "Delete";
}

<h3>@ViewBag.Title</h3>

<h4>Are you sure you want to delete this?</h4>
<div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />&nbsp;&nbsp;
            @Html.ActionLink("Cancel", "Index", "ApplicationRoles", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

src/dpc.Web/Views/ApplicationRoles/Details.cshtml
@model dpc.Web.Models.ApplicationRole

@{
    ViewBag.Title = "Details";
}

<h3>Details</h3>

<div>
    <h4>ApplicationRole</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

src/dpc.Web/Views/ApplicationRoles/Edit.cshtml
@model dpc.Web.ViewModels.ApplicationRoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h3>@ViewBag.Title</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />&nbsp;&nbsp;
                @Html.ActionLink("Cancel", "Index", "ApplicationRoles", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/dpc.Web/Views/ApplicationRoles/Index.cshtml
@model IEnumerable<dpc.Web.Models.ApplicationRole>

@{
    ViewBag.Title = "List Roles";
}

<h3>@ViewBag.Title</h3>

<p>
    @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to Admin Page", "AdminPage", "Home")
</div>